<!DOCTYPE html>
<html>
    <script>
        fetch('https://no-such-server.blabla')
        .then(Response=>Response.json())
        .catch(err=>alert(err))
        /////
        fetch('/article/promise-chaining/user.json')
        .then(Response=>Response.json())
        .then(user=>fetch(`https://api.github.com/users/${user.name}`))
        .then(Response=>Response.json())
        .then(githubUser=>new Promise((resolve,reject)=>{
            let img=document.createElement('img');
            img.src=githubUser.avatar_url;
            img.className="promise-avatar-example";
            document.body.append(img);
            setTimeout(()=>{
                img.remove();
                resolve(githubUser);
            },3000);
        }))
        .catch(error=>alert(error.message));
        //////
        new Promise((resolve,reject)=>{
            throw new Error("Whoops");
        }).catch(alert);
        ////////
        new Promise((resolve,reject)=>{
            reject(new Error("Whoops"));
        }).catch(alert);
        //////
        new Promise((resolve,reject)=>{
            resolve("ok");
        }).then((result)=>{
            throw new Error("Whoops");
        }).catch(alert);
        ////////
        new Promise((resolve,reject)=>{
            resolve("ok");
        }).then((result)=>{
            balabla();
        })
        .catch(alert);
        ////////
        new Promise((resolve,reject)=>{
            throw new Error("Whoops");
        }).catch(function(error){
            alert("the error is handled,continue normally");
        }).then(()=>alert("Next successful handleer runs"));
        //////
        new Promise((resolve,reject)=>{
            throw new Error("Whoops");
        }).catch(function(error){
            if(error instanceof URIError){
                ////////
            }else{
                alert("cant handle such error");
                throw error;
            }
        }).then(function(){
            ///////
        }).catch(error=>{
            alert(`the unkonow error has oocurred${error}`);
        });
        ////
        new Promise(function(){
            noSuchFunction();
        })
        .then(()=>{
            /////////
        })
        ///////
        window.addEventListener('unhandledreJection',function(event){
            alert(event.promise);
            alert(event.reason);
        })
        new Promise(function(){
            throw new Error("Whoops");
        });
        ////////
        new Promise(function(resolve,reject){
            setTimeout(()=>{
                throw new Error("Whoop");
            },1000);
        }).catch(alert);
        ///////
    </script>
<body>
</body>
</html>